version: '3.7'
# all the containers have to declare inside services
services:
  redis-monitor:
    image: redislabs/redisinsight:1.10.1
    container_name: redis_monitor
    ports:
      - 8001:8001
  redis:
    # image name
    image: redis:6.2.3
    # container name
    container_name: redis
    # execute the command once start redis container
    command: [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    # save (persist) data and also to share data between containers
    volumes:
      - red_data:/var/lib/redis
    # redis port, this is take value from env file
    ports:
      - '6379:6379'
      # application network, each container for a service joins this network
    networks:
      - nest-chat-network

  #Docker Networks
networks:
  # All container connect in a network
  nest-chat-network:
    driver: bridge
# save (persist) data
volumes:
  red_data: {}

